<?php
namespace IronParsers\commON;

require_once __DIR__ . '/TestInit.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-11 at 15:19:04.
 */
class CommonParserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CommonParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CommonParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers IronParsers\commON\CommonParser::getCsvRecords
     * @todo   Implement testGetCsvRecords().
     */
    public function testGetCsvRecords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IronParsers\commON\CommonParser::getCommonRecords
     * @todo   Implement testGetCommonRecords().
     */
    public function testGetCommonRecords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IronParsers\commON\CommonParser::getLinkageSchema
     * @todo   Implement testGetLinkageSchema().
     */
    public function testGetLinkageSchema()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IronParsers\commON\CommonParser::getDataset
     * @todo   Implement testGetDataset().
     */
    public function testGetDataset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IronParsers\commON\CommonParser::getCsvErrors
     * @todo   Implement testGetCsvErrors().
     */
    public function testGetCsvErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IronParsers\commON\CommonParser::getCommonErrors
     * @todo   Implement testGetCommonErrors().
     */
    public function testGetCommonErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IronParsers\commON\CommonParser::getRdfN3
     * @todo   Implement testGetRdfN3().
     */
    public function testGetRdfN3()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IronParsers\commON\CommonParser::getLinkedProperty
     * @todo   Implement testGetLinkedProperty().
     */
    public function testGetLinkedProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IronParsers\commON\CommonParser::getLinkedType
     * @todo   Implement testGetLinkedType().
     */
    public function testGetLinkedType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
