<?php
  namespace IronParsers\commON;

  /**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-11 at 21:31:06.
 */
class ReaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Reader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \IronParsers\commON\Reader(__DIR__ . "/../../../_files/test.csv");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers EasyCSV\Reader::getRow
     * @todo   Implement testGetRow().
     */
    public function testGetRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasyCSV\Reader::getAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll()
    {
      $data = $this->object->getAll();
      $filename = __DIR__ .  "/../../../../tests/_files/csvTest.inc";
      $goodArray = array();
      if (is_readable($filename))
      {
        $handle = fopen($filename,"r");
        if ($handle) {
          $goodArray = fread($handle, filesize($filename));
          fclose($handle);
        }
      }
      $this->assertArrayHasKey('recordlist',$data);
      $this->assertArrayHasKey('dataset',$data);
      $this->assertArrayHasKey('linkage',$data);
      $this->assertCount(3, $data['recordlist']);
      $this->assertEquals($goodArray, serialize($data));
      //writes out a good array for testing if enabled
      //$handle = fopen($filename,"w");
      //fwrite($handle, serialize($data));
      //fclose($handle);
    }

    /**
     * @covers EasyCSV\Reader::getLineNumber
     * @todo   Implement testGetLineNumber().
     */
    public function testGetLineNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
